RedApparat/Fotoapparat

build.gradle, fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.java, fotoapparat/src/main/java/io/fotoapparat/FotoapparatSwitcher.java, fotoapparat/src/main/java/io/fotoapparat/parameter/selector/LensPositionSelectors.java, fotoapparat/src/main/java/io/fotoapparat/routine/CheckAvailabilityRoutine.java, fotoapparat/src/test/java/io/fotoapparat/FotoapparatSwitcherTest.java, fotoapparat/src/test/java/io/fotoapparat/FotoapparatTest.java, fotoapparat/src/test/java/io/fotoapparat/routine/CheckAvailabilityRoutineTest.java, gradle.properties, sample/src/main/java/io/fotoapparat/sample/MainActivity.java, sample/src/main/res/layout/activity_main.xml
=> Added API for easy switching between cameras

fotoapparat/src/main/java/io/fotoapparat/hardware/v2/surface/SetTextureBufferSizeTask.java, gradle.properties
15 is already supported, and 14 isn't much different. The only call that
surfaced lint errors is only used on api 21 or above for camera 2.
=> fotoapparat: Support API level 14

fotoapparat/src/main/java/io/fotoapparat/parameter/selector/AspectRatioSelectors.java, fotoapparat/src/test/java/io/fotoapparat/parameter/selector/AspectRatioSelectorsTest.java
Some resolutions supported by camera CCD have aspect ratios
that deviate from 16:9 and 4:3 by a small margin (ex. 16:10).
Add tolerance to aspect ratio selector, to catch all picture
sizses that would be otherwise rejected due to strict
comparison.
=> Aspect ratio selector with tolerance

fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.java, fotoapparat/src/main/java/io/fotoapparat/FotoapparatBuilder.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v1/CameraParametersDecorator.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v1/ParametersConverter.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v2/parameters/CaptureRequestBuilder.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v2/parameters/CaptureRequestFactory.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v2/parameters/ParametersProvider.java, fotoapparat/src/main/java/io/fotoapparat/hardware/v2/parameters/Request.java, fotoapparat/src/main/java/io/fotoapparat/parameter/Parameters.java, fotoapparat/src/main/java/io/fotoapparat/parameter/factory/ParametersFactory.java, fotoapparat/src/main/java/io/fotoapparat/parameter/provider/InitialParametersProvider.java, fotoapparat/src/test/java/io/fotoapparat/parameter/provider/InitialParametersProviderTest.java, sample/src/main/java/io/fotoapparat/sample/MainActivity.java
I added a jpegQuality parameter. 
I copied what was done with sensorSensitivity (except the selector, not needed here as jpegQuality is an int ranging from 0 to 100 for camera Api). I think I've set the default compression value to 95, I'm not sure I have understood everything about what I did as I was in a hurry. I tried to follow existing format conventions as I was doing it.
I integrated it to the sample and I have tested it with Camera1 (not tested with Camera2 yet)
=> add JpegQuality parameter

fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.java, fotoapparat/src/main/java/io/fotoapparat/routine/UpdateOrientationRoutine.java, fotoapparat/src/test/java/io/fotoapparat/routine/UpdateOrientationRoutineTest.java
Catch setDisplayOrientation() RuntimeException in UpdateOrientationRoutine.
This fixes issue #105.
=> Catch setDisplayOrientation() RuntimeException

fotoapparat/src/main/java/io/fotoapparat/hardware/v2/parameters/converters/RangeConverter.java, fotoapparat/src/main/java/io/fotoapparat/parameter/Size.java, fotoapparat/src/main/java/io/fotoapparat/parameter/range/ContinuousRange.java, fotoapparat/src/main/java/io/fotoapparat/parameter/range/DiscreteRange.java, fotoapparat/src/main/java/io/fotoapparat/parameter/range/EmptyRange.java, fotoapparat/src/main/java/io/fotoapparat/parameter/range/Range.java, fotoapparat/src/main/java/io/fotoapparat/parameter/range/Ranges.java
Passing device capabilities in Bundle extras requires manual
transformations, as types do not support neither Serializable nor
Parcelable.
Implementing Parcelable is overkill, as those PODs are not
used in any performance-critical code.
Make all Capabilities members serializable, so they can be
passed into DialogFragment inside extras.
=> Make  Size and Range serializable to pass device capabilities in Bundle

fotoapparat/src/main/java/io/fotoapparat/parameter/Size.java
Number of pixels is used in some UI logic to sort available sizes. It's tedious to multiply it on each occasion.
Megapixels count is useful for presentation, the same as aspect ratio.
=> Add Size getter for pixels and megapixels

fotoapparat/src/main/java/io/fotoapparat/FotoapparatBuilder.java, fotoapparat/src/main/java/io/fotoapparat/parameter/factory/ParametersFactory.java, fotoapparat/src/main/java/io/fotoapparat/parameter/provider/InitialParametersProvider.java, fotoapparat/src/test/java/io/fotoapparat/parameter/factory/ParametersFactoryTest.java, gradle/wrapper/gradle-wrapper.properties
=> Selectors cannot be trusted, therefore we ensure their values are correct

fotoapparat/src/main/java/io/fotoapparat/exif/ExifOrientationWriter.kt, fotoapparat/src/main/java/io/fotoapparat/exif/ExifWriter.kt, fotoapparat/src/main/java/io/fotoapparat/result/transformer/SaveToFileTransformer.kt, fotoapparat/src/test/java/io/fotoapparat/result/transformer/SaveToFileTransformerTest.kt
`ExifWriter` can be simplified to just use `Ints` as its function parameter instead of `Photos`.
=> Accept rotation in degrees instead of Photos in ExifOrientationHelper

fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.kt, fotoapparat/src/main/java/io/fotoapparat/concurrent/CameraExecutor.kt, fotoapparat/src/main/java/io/fotoapparat/hardware/CameraDevice.kt, fotoapparat/src/main/java/io/fotoapparat/hardware/Device.kt, fotoapparat/src/main/java/io/fotoapparat/hardware/Executor.kt, fotoapparat/src/main/java/io/fotoapparat/result/PendingResult.kt, fotoapparat/src/main/java/io/fotoapparat/routine/camera/StartRoutine.kt, fotoapparat/src/main/java/io/fotoapparat/routine/camera/StopRoutine.kt, fotoapparat/src/main/java/io/fotoapparat/routine/orientation/StartOrientationRoutine.kt
We now differentiate between cancelable (take a picture, focus, etc.) and non-cancelable operations (start camera, stop camera).
Upon stopping the Fotoapparat instance we make sure that all cancelable operations are canceled.
=> Using only one thread for operating with camera

fotoapparat/src/main/java/io/fotoapparat/FotoapparatBuilder.kt, fotoapparat/src/main/java/io/fotoapparat/capability/Capabilities.kt, fotoapparat/src/main/java/io/fotoapparat/capability/provide/CapabilitiesProvider.kt, fotoapparat/src/main/java/io/fotoapparat/configuration/CameraConfiguration.kt, fotoapparat/src/main/java/io/fotoapparat/configuration/Configuration.kt, fotoapparat/src/main/java/io/fotoapparat/configuration/UpdateConfiguration.kt, fotoapparat/src/main/java/io/fotoapparat/hardware/Device.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/SupportedParameters.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/camera/CameraParameters.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/camera/apply/CameraParametersApplicator.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/camera/provide/CameraParametersProvider.kt, fotoapparat/src/main/java/io/fotoapparat/selector/ExposureCompensationSelectors.kt, fotoapparat/src/test/java/io/fotoapparat/parameter/camera/provide/CameraParametersProviderTest.kt, fotoapparat/src/test/java/io/fotoapparat/test/TestObjectFactory.kt
Hopefully this is more helpful than it is trouble. I am not entirely sure about my unit tests. 
Since different devices will return a different IntRange for exposure compensation, I figured the best way to implement it would be with the typical highest, lowest and manual selectors.
In addition to those selectors I added an autoExposure selector which returns the exposure compensation back to the default zero. It isn’t strictly necessary since one could set it manually to zero themselves. I can remove it if you see fit.
=> Support exposure compensation

fotoapparat/src/main/java/io/fotoapparat/capability/Capabilities.kt, fotoapparat/src/main/java/io/fotoapparat/capability/provide/CapabilitiesProvider.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/SupportedParameters.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/Zoom.kt, fotoapparat/src/main/java/io/fotoapparat/routine/zoom/UpdateZoomLevelRoutine.kt, fotoapparat/src/test/java/io/fotoapparat/parameter/camera/provide/CameraParametersProviderTest.kt, fotoapparat/src/test/java/io/fotoapparat/routine/zoom/UpdateZoomLevelRoutineTest.kt, fotoapparat/src/test/java/io/fotoapparat/test/TestObjectFactory.kt, sample/src/main/java/io/fotoapparat/sample/MainActivity.kt
Hello, guys!
I think it will be useful if you add "maxZoom" value into camera capabilities. Little use-case: you want to create pinch-zoom camera view, and you need max zoom level value for correct zoom step value calculations according to fingers travelling distance calculations.
=> Add "max zoom" value into camera capabilities.

fotoapparat/src/main/java/io/fotoapparat/FotoapparatBuilder.kt, sample/src/main/AndroidManifest.xml, sample/src/main/java/io/fotoapparat/sample/ActivityJava.java
I see getting the `FocusView` to work with the `CameraView` you need to pass its reference in to the Fotoapparat constructor.  (I was actually expecting to set the FilterView through the Fotoapparat builder).
Here is an updated Java activity that uses the new constructor.
=> Added focus view to Java example activity

fotoapparat/src/main/java/io/fotoapparat/characteristic/LensPositionCharacteristic.kt
Added case for `lensPosition==2`. Fixes exception on some rare devices with incorrect camera API implementation.
=> Add special handling for external lens positions (Fixes #224)

gradle.properties
Solves the following build error
`
Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
`
By setting org.gradle.configureondemand to false as stated in the error message, it doesn't work so it seems that there is a bug in the configuration that could be solved by removing the property from the file.
=> Remove configureondemand gradle configuration to fix build issue

fotoapparat/src/main/res/values/strings.xml
The string resource `app_name` is present from the artifact, which shouldn't be as this is a library and it should be agnostic to the consumer app.
Im deleting the whole resource file, as it's the only entry in it.
=> Remove app_name from library

fotoapparat/src/main/java/io/fotoapparat/result/Photo.kt
`BitmapFactory.decodeByteArray` returns `null` when `inJustDecodeBounds == true`, the proper way to read the size is to read the `outWidth` and `outHeight` properties of the options after the call.
=> Fix a crash when trying to access with size of a Photo

fotoapparat-adapters/rxjava/build.gradle, fotoapparat-adapters/rxjava2/build.gradle, fotoapparat/build.gradle, sample/build.gradle
I've created a C# binding library for Fotoapparat so I'm able to use it in a Xamarin based Android app.
One of the issues I encountered was that source code could not properly be desugared, the reason being that the source and target compatibility was not set. In this PR I've set the source and target compatibility to 1.8 for both the Fotoapparat library as well as the rxjava* dependencies (though perhaps it's not really needed for rxjava, I was thinking it couldn't harm).
=> Set source and target compatibility to Java 1.8 for library and dependencies

fotoapparat/src/main/java/io/fotoapparat/characteristic/LensPosition.kt, fotoapparat/src/main/java/io/fotoapparat/hardware/orientation/Orientation.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/AntiBandingMode.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/Flash.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/FocusMode.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/Zoom.kt, fotoapparat/src/main/java/io/fotoapparat/result/FocusResult.kt
Previously doing `Flash.Off.toString()` would return something like `io.fotoapparat.parameter.Flash$Off@a486ccc`, now it will return `Flash.Off`.
=> Make all the configuration objects have nicer toString values

fotoapparat/src/main/java/io/fotoapparat/hardware/orientation/OrientationSensor.kt
**Bug:** When activity locked in sensorLandscape in AndroidManifest.xml, when the user rotates the device 180 degrees, most of the time the orientation of the preview will be upside down. The user needs to shake the device in order to reset the preview
**Analysis:** When the rotation happens the screen orientation has not been updated yet. Then the orientation does not update anymore (unless you shake the device)
**Fix:** Each time the orientation updates, also check if the screen orientation has updated too.
=> fix: preview orientation in sensorLandscape

fotoapparat/src/main/java/io/fotoapparat/parameter/FpsRange.kt, fotoapparat/src/main/java/io/fotoapparat/parameter/Resolution.kt, fotoapparat/src/main/java/io/fotoapparat/result/Photo.kt
Using `lazy` create an extra field, requires synchronization and causes primitives to be boxed. It shouldn't used if the operation is `O(1)` and doesn't require a lot of allocations.
=> Remove lazy delegates where they aren't needed

fotoapparat/src/main/java/io/fotoapparat/result/transformer/BitmapPhotoTransformer.kt
I'm looking for ways to optimise memory usage in my app, and found some things in `BitmapPhotoTransformer` that i think can be improved.
1) There is `inSampleSize` calculation being done for decoding options, but it is never used because of typo.
2) We can skip creating another bitmap with `Bitmap.createScaledBitmap` if we add scaling step to decoding.
This way, if we want to scale down image while retaining original aspect ratio we skip `Bitmap.createScaledBitmap`, thus avoiding another bitmap allocation.
If we need to scale irregardless of aspect ratio, then `createScaledBitmap` will be used, but on already scaled down by biggest side version of the image, which is also a plus.
I also tried to measure performance benefit of memory usage.
I've modified sample to use …
=> Fix unused inSampleSize and add scaling to decoding step
